//
//  UITableViewViewController.m
//  ASDK Demo
//
//  Created by Kai Schaller on 1/15/15.
//  Copyright (c) 2015 Kai Schaller. All rights reserved.
//

#import "UITableViewViewController.h"
#import "MurrayCell.h"

static const CGFloat kNumberOfRows = 50;
static const CGFloat kImageSize = 80;

@interface UITableViewViewController ()

@property (strong, nonatomic) NSArray *placeholders;
@property (strong, nonatomic) NSArray *imageSizes;

@end

@implementation UITableViewViewController

#pragma mark - Lifecycle

- (void)viewDidLoad {
    [super viewDidLoad];
    
    _placeholders = @[
                      @"Minions ipsum tatata bala tu hana dul sae tatata bala tu butt. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Gelatooo bananaaaa tank yuuu! Ti aamoo! Me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Tatata bala tu bananaaaa. Butt butt butt uuuhhh bappleees bappleees jeje poopayee me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Ti aamoo! Baboiii. Poopayee po kass po kass daa poulet tikka masala wiiiii butt wiiiii potatoooo po kass. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii underweaaar po kass poopayee la bodaaa para tú. Ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"underweaaar tank yuuu! Hana dul sae. Poulet tikka masala me want bananaaa! Butt belloo! Bee do bee do bee do uuuhhh jeje. Uuuhhh tank yuuu! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii bee do bee do bee do tulaliloo underweaaar po kass jeje para tú chasy aaaaaah. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Jeje tank yuuu! Me want bananaaa! Tulaliloo aaaaaah poopayee para tú gelatooo uuuhhh hana dul sae tank yuuu! Chasy baboiii para tú hahaha baboiii tank yuuu! Hana dul sae chasy jeje potatoooo bee do bee do bee do. Hana dul sae underweaaar uuuhhh tulaliloo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Jeje bee do bee do bee do baboiii poopayee para tú po kass butt para tú la bodaaa. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Underweaaar la bodaaa wiiiii aaaaaah jiji tank yuuu! Jiji tulaliloo para tú. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah pepete po kass hahaha butt uuuhhh aaaaaah tank yuuu! Jeje wiiiii para tú. Tank yuuu! tatata bala tu daa aaaaaah jiji butt. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Potatoooo hana dul sae gelatooo poopayee. Baboiii hahaha ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Belloo! Wiiiii me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú. Poopayee me want bananaaa! Tank yuuu! Po kass bee do bee do bee do belloo! Pepete. Jeje underweaaar bappleees tulaliloo hana dul sae. Gelatooo ti aamoo! Wiiiii belloo! Gelatooo chasy poulet tikka masala. Poopayee ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Wiiiii jeje tatata bala tu bappleees. Jiji daa belloo! Tulaliloo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah me want bananaaa! Uuuhhh jeje. Tatata bala tu la bodaaa jiji chasy para tú la bodaaa baboiii underweaaar. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Butt poopayee me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú gelatooo hana dul sae chasy belloo! Tatata bala tu potatoooo aaaaaah me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Hahaha chasy. Aaaaaah pepete jeje potatoooo. Baboiii tatata bala tu para tú gelatooo hana dul sae gelatooo poopayee baboiii bananaaaa tatata bala tu. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Minions ipsum tatata bala tu hana dul sae tatata bala tu butt. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Gelatooo bananaaaa tank yuuu! Ti aamoo! Me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Tatata bala tu bananaaaa. Butt butt butt uuuhhh bappleees bappleees jeje poopayee me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Ti aamoo! Baboiii. Poopayee po kass po kass daa poulet tikka masala wiiiii butt wiiiii potatoooo po kass. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii underweaaar po kass poopayee la bodaaa para tú. Ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"underweaaar tank yuuu! Hana dul sae. Poulet tikka masala me want bananaaa! Butt belloo! Bee do bee do bee do uuuhhh jeje. Uuuhhh tank yuuu! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Baboiii bee do bee do bee do tulaliloo underweaaar po kass jeje para tú chasy aaaaaah. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Jeje tank yuuu! Me want bananaaa! Tulaliloo aaaaaah poopayee para tú gelatooo uuuhhh hana dul sae tank yuuu! Chasy baboiii para tú hahaha baboiii tank yuuu! Hana dul sae chasy jeje potatoooo bee do bee do bee do. Hana dul sae underweaaar uuuhhh tulaliloo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Jeje bee do bee do bee do baboiii poopayee para tú po kass butt para tú la bodaaa. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Underweaaar la bodaaa wiiiii aaaaaah jiji tank yuuu! Jiji tulaliloo para tú. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah pepete po kass hahaha butt uuuhhh aaaaaah tank yuuu! Jeje wiiiii para tú. Tank yuuu! tatata bala tu daa aaaaaah jiji butt. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Potatoooo hana dul sae gelatooo poopayee. Baboiii hahaha ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Belloo! Wiiiii me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú. Poopayee me want bananaaa! Tank yuuu! Po kass bee do bee do bee do belloo! Pepete. Jeje underweaaar bappleees tulaliloo hana dul sae. Gelatooo ti aamoo! Wiiiii belloo! Gelatooo chasy poulet tikka masala. Poopayee ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Wiiiii jeje tatata bala tu bappleees. Jiji daa belloo! Tulaliloo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah me want bananaaa! Uuuhhh jeje. Tatata bala tu la bodaaa jiji chasy para tú la bodaaa baboiii underweaaar. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Butt poopayee me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú gelatooo hana dul sae chasy belloo! Tatata bala tu potatoooo aaaaaah me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Hahaha chasy. Aaaaaah pepete jeje potatoooo. Baboiii tatata bala tu para tú gelatooo hana dul sae gelatooo poopayee baboiii bananaaaa tatata bala tu. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Jeje bee do bee do bee do baboiii poopayee para tú po kass butt para tú la bodaaa. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Underweaaar la bodaaa wiiiii aaaaaah jiji tank yuuu! Jiji tulaliloo para tú. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah pepete po kass hahaha butt uuuhhh aaaaaah tank yuuu! Jeje wiiiii para tú. Tank yuuu! tatata bala tu daa aaaaaah jiji butt. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Potatoooo hana dul sae gelatooo poopayee. Baboiii hahaha ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Belloo! Wiiiii me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú. Poopayee me want bananaaa! Tank yuuu! Po kass bee do bee do bee do belloo! Pepete. Jeje underweaaar bappleees tulaliloo hana dul sae. Gelatooo ti aamoo! Wiiiii belloo! Gelatooo chasy poulet tikka masala. Poopayee ti aamoo! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Wiiiii jeje tatata bala tu bappleees. Jiji daa belloo! Tulaliloo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Aaaaaah me want bananaaa! Uuuhhh jeje. Tatata bala tu la bodaaa jiji chasy para tú la bodaaa baboiii underweaaar. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Butt poopayee me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      @"Para tú gelatooo hana dul sae chasy belloo! Tatata bala tu potatoooo aaaaaah me want bananaaa! Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo. Baboiii tulaliloo hahaha bananaaaa bappleees poulet tikka masala tulaliloo la bodaaa potatoooo baboiii tank yuuu! Hahaha uuuhhh gelatooo pepete potatoooo.",
                      ];
    
    // Generate slightly random sizes for placeholder images.
    NSMutableArray *imageSizes = [NSMutableArray arrayWithCapacity:kNumberOfRows];
    for (NSInteger i = 0; i < kNumberOfRows; i++) {
        u_int32_t deltaX = arc4random_uniform(10) - 5;
        u_int32_t deltaY = arc4random_uniform(10) - 5;
        CGSize size = CGSizeMake(350 + 2 * deltaX, 350 + 4 * deltaY);
        
        [imageSizes addObject:[NSValue valueWithCGSize:size]];
    }
    self.imageSizes = imageSizes;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
    NSLog(@"memory warning");
}

#pragma mark - Utility

- (NSDictionary *)textStyle {
    UIFont *font = [UIFont fontWithName:@"HelveticaNeue" size:14];
    
    NSMutableParagraphStyle *style = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
    style.paragraphSpacing = 0.5 * font.lineHeight;
    style.hyphenationFactor = 1;
    
    return @{ NSFontAttributeName: font,
              NSParagraphStyleAttributeName: style };
}

#pragma mark - Table view data source

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    MurrayCell *cell = [tableView dequeueReusableCellWithIdentifier:@"MurrayCell"];

    NSValue *sizeValue = self.imageSizes[indexPath.row];
    CGSize size = sizeValue.CGSizeValue;
    NSURL *url = [NSURL URLWithString:[NSString stringWithFormat:@"http://fillmurray.com/%zd/%zd", (NSInteger)roundl(size.width), (NSInteger)roundl(size.height)]];
    
    UIImageView *imageView = cell.murrayImageView;
    imageView.image = nil;
    
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSData *imageData = [NSData dataWithContentsOfURL:url];
        UIImage *image = [UIImage imageWithData:imageData];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            imageView.image = image;
        });
    });
    
    UILabel *label = cell.murrayLabel;
    label.attributedText = [[NSAttributedString alloc] initWithString:[self.placeholders objectAtIndex:indexPath.row] attributes:[self textStyle]];
    
    return cell;
};

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return kNumberOfRows;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    // Get attributed string.
    NSAttributedString *attributedString = [[NSAttributedString alloc] initWithString:[self.placeholders objectAtIndex:indexPath.row] attributes:[self textStyle]];
    
    // Get size of text.
    CGRect rect = [attributedString boundingRectWithSize:CGSizeMake(300, CGFLOAT_MAX) options:(NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading) context:nil];
    
    CGFloat requiredHeight = MAX(kImageSize, rect.size.height) + arc4random_uniform(500);
    
    return requiredHeight;
}

#pragma mark - Table view delegate

@end
